" TODO:
"   Create a githook to create ctags when committing (or pushing, or w/e)
" Features to get more familiar with
"   Tabs (tabe <file>)
"   easy-align plugin
"   marks
"   ctags
"   fzf
"   folds
"   quickfix window as used in https://opensource.com/article/21/12/vanilla-vim-config


"----- Mac Defaults ---- "
" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup nobackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup nobackup

"------ Vim Plugins ------------
" Incompatible plugins
if has('syntax') && has('eval')
  packadd! matchit
end

"------ Put Plugins Here -------
call plug#begin()
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'NoahTheDuke/vim-just'
Plug 'tpope/vim-fugitive'
Plug 'liuchengxu/vim-which-key'
Plug 'morhetz/gruvbox'
" Run :PlugInstall after installation
"-------------------------------
call plug#end()

" EasyAlign Binding
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)


"------ Mechanical Changes -----
set number relativenumber            " Relative line numbers
set tabstop=4                        " 1 tab = 4 spaces
set shiftwidth=4                     " Number of spaces to use for each step of (auto)indent
set expandtab                        " Convert tabs to spaces
set smartindent                      " Enable smart autoindenting when starting a new line
set scrolloff=10                     " Keep at least 10 lines above and below cursor while scrolling
set sidescrolloff=10                 " Keep at least 10 lines above and below the cursor in
set ignorecase                       " Ignore case when searching
set smartcase                        " Searching is case-sensitive only if the pattern contains uppercase chars
set linebreak                        " Prevent wrap from cutting word in half
set path+=**                         " Allow find command to search down into subfolders
set wildmenu                         " Display all matching files for tab complete
set nocompatible                     " Don't pretend to be vi
set modelines=0                      " CVE-2007-2438
set backspace=2                      " more powerful backpacing
set timeoutlen=200                   " Delay before which-key popup appears after leader
set ttimeout ttimeoutlen=50          " Don't wait timeoutlen for terminal key codes (skip_defaults_vim drops this)
set hidden                           " Allow switching from modified buffers
let g:fzf_layout = { "down": "40%" } " Disable popup fzf window

let skip_defaults_vim=1


"" netrw                  
syntax enable              " Turn on syntax highlighting
filetype plugin indent on  " Load plugin file for detected filetype
let g:netrw_banner=0       " Disable annoying banner
let g:netrw_browse_split=4 " Open in prior window
let g:netrw_altv=1         " Open splits to the right
let g:netrw_liststyle=3    " Tree view
let g:netrw_list_hide=''
augroup netrw_config
  autocmd!
  autocmd FileType netrw let g:netrw_list_hide = netrw_gitignore#Hide() . ',\(^\|\s\s\)\zs\.\S\+'
augroup END



"+++++++++++++++++++"
"----- HOTKEYS -----"
"+++++++++++++++++++"

" Autocomplete
set autocomplete
set complete=.^5,w^5,b^5,u^5
set completeopt=popup

inoremap <silent><expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <silent><expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

let g:mapleader=","
let g:maplocalleader="_"

" Fuzzy searching
nnoremap <leader><leader> :GFiles<cr>
nnoremap <leader>b :Buffers<cr>
nnoremap <leader>t :Tags<cr>
nnoremap <leader>f :BTags<cr>
nnoremap <leader>h :History<cr>
nnoremap <leader>. :Files<cr>


" buffers and quickfix
function! ToggleQuickFix()
  if empty(filter(getwininfo(), 'v:val.quickfix'))
    copen
  else
    cclose
  endif
endfunction
nnoremap <leader>w :call ToggleQuickFix()<cr>
nnoremap <leader>d :bd<cr>

" searching ang grepping
nnoremap <leader>g :copen<cr>:Ggrep!<SPACE>
nnoremap K :Ggrep "\b<C-R><C-W>\b"<cr>:cw<cr>
nnoremap <leader>s :set hlsearch! hlsearch?<cr>

" Clear search highlights
nnoremap <leader>s :set hlsearch! hlsearch?<cr>

" Generate ctags file
nnoremap <leader>c :!ctags -R .<cr><cr>

" Navigate through visual lines when they are wrapped at the end.
nnoremap j gj
nnoremap k gk
xnoremap j gj
xnoremap k gk

" Easier movement between split windows
nmap gh <C-w>h
nmap gj <C-w>j
nmap gk <C-w>k
nmap gl <C-w>l

" ----- vim-which-key -----
nnoremap <silent> <leader> :<c-u>WhichKey ','<cr>
vnoremap <silent> <leader> :<c-u>WhichKeyVisual ','<cr>

let g:which_key_map = {}

let g:which_key_map['<leader>']  = ['GFiles', 'fuzzy-find-git-files']
let g:which_key_map.b            = ['Buffers', 'fzf-buffers']
let g:which_key_map.t            = ['Tags', 'fzf-tags']
let g:which_key_map.f            = ['BTags', 'fzf-buffer-tags']
let g:which_key_map.h            = ['History', 'fzf-file-history']
let g:which_key_map['.']         = ['Files', 'fzf-find-files']
let g:which_key_map.w            = ['call ToggleQuickFix()', 'toggle-quickfix']
let g:which_key_map.d            = ['bd', 'delete-buffer']
let g:which_key_map.g            = ['copen | Ggrep!', 'grep-and-open-quickfix']
let g:which_key_map.s            = ['set hlsearch! hlsearch?', 'toggle-search-highlight']
let g:which_key_map.c            = ['!ctags -R .', 'generate-ctags']

call which_key#register(',', 'g:which_key_map')


" Set sensible highlighting on braces that does not obscure text
highlight MatchParen cterm=underline ctermbg=black ctermfg=NONE
highlight MatchParen gui=underline guibg=black guifg=NONE
set title "Show filename in status line


" Theme
set background=dark
colorscheme seaweed-tea_bright

" Force true colors on
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
