import = [
    #https://github.com/alacritty/alacritty-theme
    #"~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml"
    #"~/.config/alacritty/themes/themes/hardhacker.toml"
    #"~/.config/alacritty/themes/themes/moonfly.toml"
    "~/.config/alacritty/themes/themes/hardhacker.toml"
]

[font.normal]
family = "IBM Plex Mono"

[font]
size = 14 

[cursor]
style = { shape = "beam", blinking = "always" }

